### ISSUE TITLE
Ensure there are no empty labels

### ISSUE THREAD

**Issue by SebiderSushi** [Phosphorus-M/Cheat-Parser#1]
Thanks for this hacky little program!

Using melonDS 0.9.4, the .mch file won't get loaded if any of the labels are empty.
the parser could ensure that no label is an empty string by setting it to `Unknown` or `(new category)` / `(new AR code)` [default values when creating entries in the UI]

unless you think it would better if melonDS would be patched to handle empty label strings.

**Comment by SebiderSushi** [comment]
i think the issue is mostly cheats that are not in any category so changing this line:
https://github.com/Phosphorus-M/Cheat-Parser/blob/b30c4d313076d87eb1e74f8ab34b855cd466cad0/src/main.rs#L59
to initialize the new_category with a not-empty string should be useful

**Comment by Phosphorus-M** [comment]
Yes basically it is, I'm going to change this part to assign a default value to the string.

**Comment by SebiderSushi** [comment]
Thanks! That should do. Very nice.
